export default [
    {
        id:"10",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc3G6PyF6P8MYwXo-d6UBzkKvKD4697hYRHA&s",
        name:"Baskin Robbins",
        rating:4.4,
        time:"30-40",
        adress:"Residency Road, Ashok Nagar",
        ratings:"1k",
        cost_for_two:500,
        menu:[
            {
                id:"20",
                name:"Recommended",
                items:[
                    {
                        id:"101",
                        name:"Lotus Biscoff Ice Cream Roll Cake",
                        price:905.93,
                        description:"Spange cake with Lotus Biscoff ice cream & caramel ribbon, topped with Biscoff Crumbles",
                        rating:4.1,
                        ratings:43,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqPWrTb2ZQWcVWEovM3W3t4K9CH89fDnXpXw&s",
                        veg:true,
                        bestSeller:false,
                        quantity:1,
                    },
                    {
                        id:"102",
                        name:"Strawberry Cheesecake",
                        price:290,
                        description:"Baked cheesecake with Very Berry Strawberry ice cream, sauce and whipped cream",
                        rating:4.3,
                        ratings:34,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpIwMcxOC7UWL0ueFC7VsbqBr1yy4hMVmXHQ&s",
                        veg:false,
                        bestSeller:true,
                        quantity:1,
                    },
                    {
                        id:"103",
                        name:"Blueberry N' White Chocolate",
                        price:99,
                        description:"Exotic white chocolate ice cream with sweet blueberries",
                        rating:4.5,
                        ratings:56,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6EhfFpRDyGKSSu0uUkaZW9ISP3g4pC4TqkQ&s",
                        veg:true,
                        bestSeller:false,
                        quantity:1,
                    },
                    {
                        id:"104",
                        name:"Dark knight cake",
                        price:600,
                        description:"Dark chocolate cake decorated with shards of chocolate with forest design",
                        rating:4.3,
                        ratings:34,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ83XrWg2hkr7JrBQn90e_CVZkRLycW_PoSg&s",
                        veg:true,
                        bestSeller:true,
                        quantity:1,
                    },
                    {
                        id:"105",
                        name:"Nutella Roacher cake",
                        price:799,
                        description:"Chocolate sponge layers, sandwiched with nutella paste and ferrero rocher bits. Recommended for all nutella lovers out there!",
                        rating:4.5,
                        ratings:56,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyvFc4rhynahkXlLiDs0Ug3M3laHvY38BxcA&s",
                        veg:true,
                        bestSeller:false,
                        quantity:1,
                    },
                ]
                    
            },
            
        ]
    },
    {
        id:"11",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDsvOUvuui43FYfV_2sJ3AlDhIl8TV7guSZg&s",
        name:"7th Heaven",
        rating:4.4,
        time:"30-40",
        adress:"Residency Road, Ashok Nagar",
        ratings:"1k",
        cost_for_two:500,
        menu:[
            {
                id:"21",
                name:"Recommended",
                items:[
                    {
                        id:"201",
                        name:"Coffee Cake",
                        price:550,
                        description:"This cake is a coffee lovers delight. It uses a light and airy chocolate based cake with a coffee flavoured frosting inside and outside",
                        rating:4.1,
                        ratings:43,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMykpLsEoDuo8fs22xugwTbiiGAwp1bmHycQ&s",
                        veg:true,
                        bestSeller:false,
                        quantity:1,
                    },
                    {
                        id:"202",
                        name:"Dark knight cake",
                        price:600,
                        description:"Dark chocolate cake decorated with shards of chocolate with forest design",
                        rating:4.3,
                        ratings:34,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ83XrWg2hkr7JrBQn90e_CVZkRLycW_PoSg&s",
                        veg:true,
                        bestSeller:true,
                        quantity:1,
                    },
                    {
                        id:"203",
                        name:"Nutella Roacher cake",
                        price:799,
                        description:"Chocolate sponge layers, sandwiched with nutella paste and ferrero rocher bits. Recommended for all nutella lovers out there!",
                        rating:4.5,
                        ratings:56,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyvFc4rhynahkXlLiDs0Ug3M3laHvY38BxcA&s",
                        veg:true,
                        bestSeller:false,
                        quantity:1,
                    },
                    {
                        id:"204",
                        name:"Lotus Biscoff Ice Cream Roll Cake",
                        price:905.93,
                        description:"Spange cake with Lotus Biscoff ice cream & caramel ribbon, topped with Biscoff Crumbles",
                        rating:4.1,
                        ratings:43,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqPWrTb2ZQWcVWEovM3W3t4K9CH89fDnXpXw&s",
                        veg:true,
                        bestSeller:false,
                        quantity:1,
                    },
                    {
                        id:"205",
                        name:"Strawberry Cheesecake",
                        price:290,
                        description:"Baked cheesecake with Very Berry Strawberry ice cream, sauce and whipped cream",
                        rating:4.3,
                        ratings:34,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpIwMcxOC7UWL0ueFC7VsbqBr1yy4hMVmXHQ&s",
                        veg:false,
                        bestSeller:true,
                        quantity:1,
                    },
                    
                ]
            },
            
        ]
    },
    {
        id:"12",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpkvvSC5S0PfaJeqcOwkoyIgOsthe6IVdTLA&s",
        name:"WarmOven Cake & Desserts",
        rating:4.4,
        time:"30-40",
        adress:"Residency Road, Ashok Nagar",
        ratings:"1k",
        cost_for_two:500,
        menu:[
            {
                id:"31",
                name:"Recommended",
                items:[
                    {
                        id:"301",
                        name:"Molten La Petit",
                        price:349,
                        description:"Serves 1|A scrumptious Bento Cake made with layers of fresh chocolate sponge, silky chocolate ganache, a sprinkle of chocolates filled cookie chunks and topped with chocolate curls and chocolate filled cookies.",
                        rating:4.1,
                        ratings:43,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWBTHmtJQk-0pOO_SrV-n72pGOkXhNwlksmA&s",
                        veg:true,
                        bestSeller:false,
                        quantity:1,
                    },
                    {
                        id:"302",
                        name:"Blueberry Jar Cake",
                        price:189,
                        description:"A fruity combination of light cake & whipped cream finished off with a delicious Blueberry topping. This super moist jar cake bursts with the distinct Blueberry flavour.",
                        rating:4.3,
                        ratings:34,
                        image:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/ygd7jyuzodw2q4q5oora",
                        veg:true,
                        bestSeller:true,
                        quantity:1,
                    },
                    {
                        id:"303",
                        name:"Hazelnut Gateau Cake",
                        price:949,
                        description:"Serves 6 | An elegant cake that has the nutty flavour of Hazelnut through layers of a rich chocolate sponge. The cake is topped off with a smooth Belgian Chocolate ganache and crunchy toasted hazelnuts ",
                        rating:4.5,
                        ratings:56,
                        image:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,h_600/ucviz5pzkzzmsbfvvpgn",
                        veg:true,
                        bestSeller:false,
                        quantity:1,
                    },
                    {
                        id:"304",
                        name:"Lotus Biscoff Ice Cream Roll Cake",
                        price:905.93,
                        description:"Spange cake with Lotus Biscoff ice cream & caramel ribbon, topped with Biscoff Crumbles",
                        rating:4.1,
                        ratings:43,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqPWrTb2ZQWcVWEovM3W3t4K9CH89fDnXpXw&s",
                        veg:true,
                        bestSeller:false,
                        quantity:1,
                    },
                    {
                        id:"305",
                        name:"Strawberry Cheesecake",
                        price:290,
                        description:"Baked cheesecake with Very Berry Strawberry ice cream, sauce and whipped cream",
                        rating:4.3,
                        ratings:34,
                        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpIwMcxOC7UWL0ueFC7VsbqBr1yy4hMVmXHQ&s",
                        veg:false,
                        bestSeller:true,
                        quantity:1,
                    },
                    
                ]
            },
            
        ]
    },
]